SUPABASE_URL = "https://ho121nujwuyjppukqotmfiv.supabase.co"
SUPABASE_KEY = "111"

N8N_GEN_URL = "https://virshi.app.n8n.cloud/webhook/webhook/generate-prompts"
N8N_ANALYZE_URL = "https://virshi.app.n8n.cloud/webhook/webhook/run-analysis"
N8N_RECO_URL = "https://virshi.app.n8n.cloud/webhook/webhook/generate-recos"
