SUPABASE_URL = "https://honujwuyjppukqotmfiv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvbnVqd3V5anBwdWtxb3RtZml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxMDc3NDIsImV4cCI6MjA4MDY4Mzc0Mn0.AX7EBrI-pHuGZTmfK5X5Ktb25FuVUTxJGwH6ikJbS-0"

N8N_WEBHOOK_URL = "https://virshi.app.n8n.cloud/webhook/webhook/generate-prompts"
N8N_REC_WEBHOOK = "https://virshi.app.n8n.cloud/webhook-test/webhook/run-analysis"
