SUPABASE_URL = "https://ho121nujwuyjppukqotmfiv.supabase.co"
SUPABASE_KEY = "111"

N8N_WEBHOOK_URL = "https://virshi.app.n8n.cloud/webhook/webhook/generate-prompts"
N8N_REC_WEBHOOK = "https://virshi.app.n8n.cloud/webhook-test/webhook/run-analysis"
